/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@stencil/router';
import {
  BadgeColor,
} from './components/widgets/badge/types';
import {
  BtnColor,
  BtnType,
} from './components/widgets/button/types';
import {
  Todo,
} from './components/page-todo/types';


export namespace Components {
  interface AppHome {}
  interface AppProfile {
    'match': MatchResults;
  }
  interface AppRoot {}
  interface KotoBadge {
    'color': BadgeColor;
  }
  interface KotoButton {
    'color': BtnColor;
    'type': BtnType;
  }
  interface KotoCheckbox {
    'checked': boolean;
    'disabled': boolean;
    'labelRender': any;
    'name': string;
    'value': string;
  }
  interface KotoContent {}
  interface KotoInput {
    'name': string;
    'placeholder': string;
  }
  interface KotoList {}
  interface KotoListItem {}
  interface KotoLogin {}
  interface KotoNotFound {}
  interface KotoPalette {
    'color': string;
  }
  interface KotoRoot {}
  interface KotoTodo {}
  interface KotoTodoItem {
    'todo': Todo;
  }
  interface KotoWidgetsPage {}
}

declare namespace LocalJSX {
  interface AppHome extends JSXBase.HTMLAttributes {}
  interface AppProfile extends JSXBase.HTMLAttributes {
    'match'?: MatchResults;
  }
  interface AppRoot extends JSXBase.HTMLAttributes {}
  interface KotoBadge extends JSXBase.HTMLAttributes {
    'color'?: BadgeColor;
  }
  interface KotoButton extends JSXBase.HTMLAttributes {
    'color'?: BtnColor;
    'type'?: BtnType;
  }
  interface KotoCheckbox extends JSXBase.HTMLAttributes {
    'checked'?: boolean;
    'disabled'?: boolean;
    'labelRender'?: any;
    'name': string;
    'value'?: string;
  }
  interface KotoContent extends JSXBase.HTMLAttributes {}
  interface KotoInput extends JSXBase.HTMLAttributes {
    'name': string;
    'placeholder'?: string;
  }
  interface KotoList extends JSXBase.HTMLAttributes {}
  interface KotoListItem extends JSXBase.HTMLAttributes {}
  interface KotoLogin extends JSXBase.HTMLAttributes {}
  interface KotoNotFound extends JSXBase.HTMLAttributes {}
  interface KotoPalette extends JSXBase.HTMLAttributes {
    'color'?: string;
  }
  interface KotoRoot extends JSXBase.HTMLAttributes {}
  interface KotoTodo extends JSXBase.HTMLAttributes {}
  interface KotoTodoItem extends JSXBase.HTMLAttributes {
    'todo'?: Todo;
  }
  interface KotoWidgetsPage extends JSXBase.HTMLAttributes {}

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-profile': AppProfile;
    'app-root': AppRoot;
    'koto-badge': KotoBadge;
    'koto-button': KotoButton;
    'koto-checkbox': KotoCheckbox;
    'koto-content': KotoContent;
    'koto-input': KotoInput;
    'koto-list': KotoList;
    'koto-list-item': KotoListItem;
    'koto-login': KotoLogin;
    'koto-not-found': KotoNotFound;
    'koto-palette': KotoPalette;
    'koto-root': KotoRoot;
    'koto-todo': KotoTodo;
    'koto-todo-item': KotoTodoItem;
    'koto-widgets-page': KotoWidgetsPage;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {



  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLKotoBadgeElement extends Components.KotoBadge, HTMLStencilElement {}
  var HTMLKotoBadgeElement: {
    prototype: HTMLKotoBadgeElement;
    new (): HTMLKotoBadgeElement;
  };

  interface HTMLKotoButtonElement extends Components.KotoButton, HTMLStencilElement {}
  var HTMLKotoButtonElement: {
    prototype: HTMLKotoButtonElement;
    new (): HTMLKotoButtonElement;
  };

  interface HTMLKotoCheckboxElement extends Components.KotoCheckbox, HTMLStencilElement {}
  var HTMLKotoCheckboxElement: {
    prototype: HTMLKotoCheckboxElement;
    new (): HTMLKotoCheckboxElement;
  };

  interface HTMLKotoContentElement extends Components.KotoContent, HTMLStencilElement {}
  var HTMLKotoContentElement: {
    prototype: HTMLKotoContentElement;
    new (): HTMLKotoContentElement;
  };

  interface HTMLKotoInputElement extends Components.KotoInput, HTMLStencilElement {}
  var HTMLKotoInputElement: {
    prototype: HTMLKotoInputElement;
    new (): HTMLKotoInputElement;
  };

  interface HTMLKotoListElement extends Components.KotoList, HTMLStencilElement {}
  var HTMLKotoListElement: {
    prototype: HTMLKotoListElement;
    new (): HTMLKotoListElement;
  };

  interface HTMLKotoListItemElement extends Components.KotoListItem, HTMLStencilElement {}
  var HTMLKotoListItemElement: {
    prototype: HTMLKotoListItemElement;
    new (): HTMLKotoListItemElement;
  };

  interface HTMLKotoLoginElement extends Components.KotoLogin, HTMLStencilElement {}
  var HTMLKotoLoginElement: {
    prototype: HTMLKotoLoginElement;
    new (): HTMLKotoLoginElement;
  };

  interface HTMLKotoNotFoundElement extends Components.KotoNotFound, HTMLStencilElement {}
  var HTMLKotoNotFoundElement: {
    prototype: HTMLKotoNotFoundElement;
    new (): HTMLKotoNotFoundElement;
  };

  interface HTMLKotoPaletteElement extends Components.KotoPalette, HTMLStencilElement {}
  var HTMLKotoPaletteElement: {
    prototype: HTMLKotoPaletteElement;
    new (): HTMLKotoPaletteElement;
  };

  interface HTMLKotoRootElement extends Components.KotoRoot, HTMLStencilElement {}
  var HTMLKotoRootElement: {
    prototype: HTMLKotoRootElement;
    new (): HTMLKotoRootElement;
  };

  interface HTMLKotoTodoElement extends Components.KotoTodo, HTMLStencilElement {}
  var HTMLKotoTodoElement: {
    prototype: HTMLKotoTodoElement;
    new (): HTMLKotoTodoElement;
  };

  interface HTMLKotoTodoItemElement extends Components.KotoTodoItem, HTMLStencilElement {}
  var HTMLKotoTodoItemElement: {
    prototype: HTMLKotoTodoItemElement;
    new (): HTMLKotoTodoItemElement;
  };

  interface HTMLKotoWidgetsPageElement extends Components.KotoWidgetsPage, HTMLStencilElement {}
  var HTMLKotoWidgetsPageElement: {
    prototype: HTMLKotoWidgetsPageElement;
    new (): HTMLKotoWidgetsPageElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'koto-badge': HTMLKotoBadgeElement;
    'koto-button': HTMLKotoButtonElement;
    'koto-checkbox': HTMLKotoCheckboxElement;
    'koto-content': HTMLKotoContentElement;
    'koto-input': HTMLKotoInputElement;
    'koto-list': HTMLKotoListElement;
    'koto-list-item': HTMLKotoListItemElement;
    'koto-login': HTMLKotoLoginElement;
    'koto-not-found': HTMLKotoNotFoundElement;
    'koto-palette': HTMLKotoPaletteElement;
    'koto-root': HTMLKotoRootElement;
    'koto-todo': HTMLKotoTodoElement;
    'koto-todo-item': HTMLKotoTodoItemElement;
    'koto-widgets-page': HTMLKotoWidgetsPageElement;
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

